### ISSUE TITLE
Memory Limits

### ISSUE THREAD

**Issue by pogzie** [mjungnickel18/papyruscs#12]
Possible to add memory limits to the parameters? Im getting OOMs when using Docker. Possibly due to https://github.com/dotnet/coreclr/issues/18044 

I've tried disabling swap but still getting OOMed. Wondering if approaching via code would be beneficial.

**Comment by mjungnickel18** [comment]
Try using 0.3.6 and beyond. It seriously reduces the menory usage. Setting - - threads should improve it further

**Comment by pogzie** [comment]
my last configuration was 1 CPU and 1Gb ram. still OOMing. my minecraft configuration is 0.5 CPU and 1gb ram so I dont think that setting more than 1gb for a map renderer doesnt make much sense, or rather counter productive. 

i've already halved the default and set 8 threads than the default 16. i havent tried 0.3.6, i will do so today.

**Comment by pogzie** [comment]
Yeah unfortunately it still cant render with 1 CPU and 1GB memory allocation. Still OOMing. 

```
[Sun Jul  7 11:56:22 2019] Memory cgroup stats for /docker/61726f76da03dd613145f0ef7c884656a2f1947a50705a0ee773dffd5d39ab44: cache:4KB rss:1048572KB rss_huge:0KB mapped_file:0KB swap:1577168KB inactive_anon:524276KB active_anon:524012KB inactive_file:4KB active_file:0KB unevictable:4KB
[Sun Jul  7 11:56:22 2019] [ pid ]   uid  tgid total_vm      rss nr_ptes swapents oom_score_adj name
[Sun Jul  7 11:56:22 2019] [31957]     0 31957     4489      313      14       74             0 entrypoint.sh
[Sun Jul  7 11:56:22 2019] [31983]     0 31983     6996      200      20       69             0 cron
[Sun Jul  7 11:56:22 2019] [31984]     0 31984     4490      313      14       75             0 generate_map.sh
[Sun Jul  7 11:56:22 2019] [31988]     0 31988  1526917   267329    1567   395930             0 PapyrusCs
[Sun Jul  7 11:56:22 2019] [ 1204]     0  1204     4548      401      14      127             0 bash
[Sun Jul  7 11:56:22 2019] Memory cgroup out of memory: Kill process 1467 (PapyrusCs) score 974 or sacrifice child
[Sun Jul  7 11:56:22 2019] Killed process 31988 (PapyrusCs) total-vm:6107668kB, anon-rss:1040024kB, file-rss:29292kB, shmem-rss:0kB
```

I've set the thread lower from the default 16 to 8. I will lower even more and see.

**Comment by pogzie** [comment]
Changed down to 4 threads still OOMing.

**Comment by mjungnickel18** [comment]
I'll try to add some flags to force Garbage Collection and further reduce the memory footprint.  Maybe that will help.
