### ISSUE TITLE
Not really an issue, Markers possible?

### ISSUE THREAD

**Issue by Pokihead** [mjungnickel18/papyruscs#15]
Hey love your mapper, in my opinion it is the best for MCBE.
My Questions is above. Is it possible to add markers? Or is something like that planned?
and does the isometric perspective is still in development?
Greetings

**Comment by barrett777** [comment]
I'll work on this, in case anyone else started looking into it

**Comment by PaulWalkerUK** [comment]
I'd be interested in seeing markers added as well. I'm not thinking of player markers though, more like annotations to the map, eg for adding place names etc. Am I right in thinking this uses Leaflet to display the map? If so, I understand that has functionality for markers and also lines/shapes etc - I don't know if that could be utilised? It would also be useful for doing things like circling areas of interest or highlighting railways etc. These could be described in a separate "annotations" file which could be passed in as a new parameter
