### ISSUE TITLE
Missing Texture(2) error

### ISSUE THREAD

**Issue by qole** [mjungnickel18/papyruscs#27]
I am getting "Missing Texture(2)" errors for "bee_nest" and "end_brick_stairs" and I can find no documentation for fixing these errors. 

I got the latest vanilla texture pack, I put the textures/blocks folder and the the two json files. textures/terrain_texture.json and textures/item_texture.json into the papyrus/textures folder, but this doesn't seem to help.

**Comment by Christian7573** [comment]
Are these errors hindering your rendering experience? I'd imagine in most worlds, they wouldn't actually show up on the map, in which case this is just a warning message and doesn't affect the output.

**Comment by crazy888** [comment]
> Are these errors hindering your rendering experience? I'd imagine in most worlds, they wouldn't actually show up on the map, in which case this is just a warning message and doesn't affect the output.

Rendering works fine but you will never know where the bees are :)

**Comment by qole** [comment]
The end_brick_stairs error is definitely affecting the rendering experience, as there are several places, especially in The End dimension, where they are visible on the map. They simply render as black squares on the map.

**Comment by achton** [comment]
@qole Not sure about `end_brick_stairs` but the bee textures are working in the latest release from `master`. I can't find the end brick stairs textures in the [Vanilla resource pack](https://aka.ms/resourcepacktemplate).

**Comment by karpana** [comment]
assembled a quick test on my realm, and validated it with the self-compiled version of commit #cc32985.
Screenshot attached. (end blocks included, slabs, blocks, stairs and the end blocks themselves.

Everything seems good to go, as this all seems resolved.
![TextureTest](https://user-images.githubusercontent.com/15716173/87250706-64627280-c42c-11ea-8aa1-e7ea0d8e008e.png)

**Comment by karpana** [comment]
Installed 0.5.1 update on my linux server.
This is all working correctly.

This @bennydiamond I believe this can be closed as "resolved".

**Comment by qole** [comment]
I agree, this is resolved under the latest Linux version. Also the new nether blocks are all there.
