### ISSUE TITLE
On windows, with 1.16 BDS, hot backups should work right?

### ISSUE THREAD

**Issue by voult2** [mjungnickel18/papyruscs#54]
However, the executable is terminating with this error:

NOTICE: Hot-backups are currently not supported on Windows. Please enable "StopBeforeBackup" in the "configuration.json" instead.

Could you please check?

**Comment by clarkx86** [comment]
Due to this being related to [vellum](https://github.com/clarkx86/vellum), can you open a new issue there :)?

**Comment by voult2** [comment]
Yeah of course.. sorry
