### ISSUE TITLE
Papyrus fails if bedrock server is currently running

### ISSUE THREAD

**Issue by jmartin657** [mjungnickel18/papyruscs#74]
Process fails if the server is currently running because the files are in use, not sure why you dont add a tmp folder in papyrus as an option. Just did the work around by using a batch file that just copies the folder before hand but should really be done by the application, if not by default at least with a tmp folder argument

Xcopy /E /I /d /Y "D:\OneDrive\Minecraft Server\worlds\Bedrock" "D:\OneDrive\Minecraft Server\Map\tmp_world_copy" &
cd /d "D:\OneDrive\Minecraft Server\papyruscs" &
papyruscs --world "D:\OneDrive\Minecraft Server\Map\tmp_world_copy" --output "D:\OneDrive\Minecraft Server\Map" --playericons "true"  --render_map  "false"

**Comment by clarkx86** [comment]
Check out [vellum](https://github.com/clarkx86/vellum), which does exactly what you want (and more).

**Comment by jmartin657** [comment]
Very cool, will use that for backups as I hadnt found any solution for that yet but ive already got a working solution for papyrus now
